In [191]:
import os
import pandas as pd
import numpy as np
import matplotlib
import networkx as nx

print(os.getcwd())

BUILDING_NAME = 'Edificio1.csv'

ASCENDING_SPEED = 1.0
DESCENDING_SPEED = 2.0
HORIZONTAL_SPEED = 1.5

ASCENDING_ENERGY= 50
DESCENDING_ENERGY= 5
HORIZONTAL_ENERGY = 10

BATTERY_CAPACITY = 3600 if 'Edificio1.csv' == BUILDING_NAME else 21600 #1 Wh is 3600 J

Y_ENTRY_POINT = -12.5 if 'Edificio1.csv' == BUILDING_NAME else -20.0

/home/michele/big-project-FOR

# Reading CSV and creating pairs

In [192]:
#loading building csv data
building = pd.read_csv(BUILDING_NAME)

#setting node numbering from 1 to n
building.index += 1 

#generating all possible pairs of points (edges)
nodes_pairs = building.rename_axis('source_node').reset_index().merge(building.rename_axis('target_node').reset_index(), how='cross')

#removing self-self pairs
nodes_pairs = nodes_pairs[nodes_pairs['source_node'] != nodes_pairs['target_node']] #keeping only pairs with different points

In [193]:
first_point_cols= ['x_x','y_x','z_x']
second_point_cols=['x_y','y_y','z_y']
diff_cols= ['dx','dy','dz']

# Computing distances

In [194]:
#function to determine if two points are connected based on distance and coordinate deltas

def process_connections(dataframe):
    #distances and deltas on coordinates
    dataframe[diff_cols] = (dataframe[second_point_cols].values - dataframe[first_point_cols].values)
    dataframe['euclidean_distance'] = np.sqrt((dataframe[diff_cols]**2).sum(axis=1)) #axis=1 sum on columns 
    
    
    # conditions
    condition_near = (dataframe['euclidean_distance'] <= 4.0)
    
    
    condition_tunnel = (
        ((dataframe['dx'].abs() <= 0.5) & (dataframe['dy'].abs() <= 0.5)) | 
        ((dataframe['dy'].abs() <= 0.5) & (dataframe['dz'].abs() <= 0.5)) | 
        ((dataframe['dx'].abs() <= 0.5) & (dataframe['dz'].abs() <= 0.5))
    )
    condition_tunnel_and_not_far = (dataframe['euclidean_distance'] <= 11.0) & condition_tunnel
    
    # final connection condition
    dataframe["are_connected"] = condition_near | condition_tunnel_and_not_far
    return dataframe

In [195]:
nodes_pairs = process_connections(nodes_pairs)

nodes_pairs.head()

,source_node,x_x,y_x,z_x,target_node,x_y,y_y,z_y,dx,dy,dz,euclidean_distance,are_connected
1,1,2.5,3.25,0.0,2,-6.0,3.25,0.0,-8.5,0.0,0.0,8.500000,True
2,1,2.5,3.25,0.0,3,-6.0,11.75,0.0,-8.5,8.5,0.0,12.020815,False
3,1,2.5,3.25,0.0,4,2.5,11.75,0.0,0.0,8.5,0.0,8.500000,True
4,1,2.5,3.25,0.0,5,2.5,3.25,11.0,0.0,0.0,11.0,11.000000,True
5,1,2.5,3.25,0.0,6,-6.0,3.25,11.0,-8.5,0.0,11.0,13.901439,False

In [196]:
#computing vertical distances on z and distances on horizontal plane x,y
nodes_pairs["d_horizontal"] = np.sqrt(nodes_pairs['dx']**2 + nodes_pairs['dy']**2)
nodes_pairs["d_vertical"] = nodes_pairs['dz']

#dropping columns that are not useful anymore
nodes_pairs.drop(columns=['dx','dy','dz'], inplace=True)
nodes_pairs.drop(columns=['x_x','y_x','z_x','x_y','y_y','z_y'], inplace=True)

#keeping only connected pairs
nodes_pairs = nodes_pairs[nodes_pairs['are_connected']==True]
nodes_pairs.drop(columns=['are_connected'], inplace=True)

nodes_pairs.head(5)

    source_node  target_node  euclidean_distance  d_horizontal  d_vertical
1             1            2            8.500000      8.500000         0.0
3             1            4            8.500000      8.500000         0.0
4             1            5           11.000000      0.000000        11.0
18            1           19            4.007805      4.007805         0.0
19            1           20            1.030776      1.030776         0.0

# Function for time travel

In [197]:
#finding rows corresponding to different movement types 

d_horizontal = nodes_pairs['d_horizontal']
d_vertical = nodes_pairs['d_vertical']
rows_horizontal = (d_vertical == 0)
rows_ascending = (d_horizontal == 0) & (d_vertical > 0)
rows_descending = (d_horizontal == 0) & (d_vertical < 0)
rows_oblique_ascending = (d_horizontal != 0) & (d_vertical > 0)
rows_oblique_descending = (d_horizontal != 0) & (d_vertical < 0)

In [198]:
#function for time travel based on movement types and speeds

def compute_time_travel(dataframe):
    dataframe.loc[rows_horizontal, 'time_travel'] = dataframe.loc[rows_horizontal, 'd_horizontal'] / HORIZONTAL_SPEED

    dataframe.loc[rows_ascending, 'time_travel'] = dataframe.loc[rows_ascending, 'd_vertical'] / ASCENDING_SPEED
    dataframe.loc[rows_descending, 'time_travel'] = -dataframe.loc[rows_descending, 'd_vertical'] / DESCENDING_SPEED

    dataframe.loc[rows_oblique_ascending, 'time_travel'] = np.maximum(dataframe.loc[rows_oblique_ascending, 'd_horizontal'] / HORIZONTAL_SPEED,
                                                                     dataframe.loc[rows_oblique_ascending, 'd_vertical'] / ASCENDING_SPEED)
    
    dataframe.loc[rows_oblique_descending, 'time_travel'] = np.maximum(dataframe.loc[rows_oblique_descending, 'd_horizontal'] / HORIZONTAL_SPEED,
                                                                     -dataframe.loc[rows_oblique_descending, 'd_vertical'] / DESCENDING_SPEED)
    return dataframe

# Function for energy consumption

In [199]:
#function for energy cost based on movement types and energy consumption rates

def compute_energy_cost(dataframe):
    dataframe.loc[rows_horizontal, 'energy_consumption'] = dataframe.loc[rows_horizontal, 'd_horizontal'] * HORIZONTAL_ENERGY

    dataframe.loc[rows_ascending, 'energy_consumption'] = dataframe.loc[rows_ascending, 'd_vertical'] * ASCENDING_ENERGY
    dataframe.loc[rows_descending, 'energy_consumption'] = -dataframe.loc[rows_descending, 'd_vertical'] * DESCENDING_ENERGY

    dataframe.loc[rows_oblique_ascending, 'energy_consumption'] = (dataframe.loc[rows_oblique_ascending, 'd_horizontal'] * HORIZONTAL_ENERGY +
                                                                  dataframe.loc[rows_oblique_ascending, 'd_vertical'] * ASCENDING_ENERGY)
    
    dataframe.loc[rows_oblique_descending, 'energy_consumption'] = (dataframe.loc[rows_oblique_descending, 'd_horizontal'] * HORIZONTAL_ENERGY +
                                                                  -dataframe.loc[rows_oblique_descending, 'd_vertical'] * DESCENDING_ENERGY)
    return dataframe

# Actually computing energy and time costs for edges

In [200]:
#computing time travel and energy cost for each pair (edges)

nodes_pairs = compute_time_travel(nodes_pairs)

nodes_pairs = compute_energy_cost(nodes_pairs)

nodes_pairs.drop(columns=['d_horizontal','d_vertical', 'euclidean_distance'], inplace=True)

nodes_pairs.head(10)

    source_node  target_node  time_travel  energy_consumption
1             1            2     5.666667           85.000000
3             1            4     5.666667           85.000000
4             1            5    11.000000          550.000000
18            1           19     2.671870           40.078049
19            1           20     0.687184           10.307764
64            2            1     5.666667           85.000000
66            2            3     5.666667           85.000000
69            2            6    11.000000          550.000000
82            2           19     3.004626           45.069391
83            2           20     5.002777           75.041655

# Creating Graph with Networkx

In [201]:
#creating directed graph G from the dataframe of edges with costs

G = nx.from_pandas_edgelist(
    nodes_pairs,                                     # dataframe containing edges
    source='source_node',                            # indicating the start of the edge
    target='target_node',                            # indicating the end of the edge
    edge_attr=['time_travel', 'energy_consumption'], # edge costs
    create_using=nx.DiGraph()                        # creating an oriented graph
)

print(G.edges())

[(1, 2), (1, 4), (1, 5), (1, 19), (1, 20), (2, 1), (2, 3), (2, 6), (2, 19), (2, 20), (4, 1), (4, 3), (4, 8), (5, 1), (5, 6), (5, 8), (5, 11), (5, 12), (19, 1), (19, 2), (19, 18), (19, 20), (19, 23), (20, 1), (20, 2), (20, 17), (20, 19), (20, 24), (3, 2), (3, 4), (3, 7), (6, 2), (6, 5), (6, 7), (6, 9), (7, 3), (7, 6), (7, 8), (7, 10), (8, 4), (8, 5), (8, 7), (8, 11), (8, 12), (11, 5), (11, 8), (11, 10), (11, 12), (11, 15), (12, 5), (12, 8), (12, 9), (12, 11), (12, 16), (9, 6), (9, 10), (9, 12), (9, 13), (10, 7), (10, 9), (10, 11), (10, 14), (13, 9), (13, 14), (13, 16), (14, 10), (14, 13), (14, 15), (15, 11), (15, 14), (15, 16), (16, 12), (16, 13), (16, 15), (17, 18), (17, 20), (17, 21), (17, 50), (17, 51), (17, 60), (17, 63), (17, 64), (18, 17), (18, 19), (18, 22), (18, 50), (18, 51), (18, 57), (18, 61), (18, 62), (21, 17), (21, 22), (21, 24), (21, 27), (21, 34), (21, 35), (21, 39), (21, 54), (21, 55), (21, 57), (21, 59), (21, 60), (21, 61), (21, 62), (21, 63), (21, 64), (50, 17), (50, 18), (50, 43), (50, 44), (50, 49), (50, 54), (51, 17), (51, 18), (51, 52), (51, 55), (60, 17), (60, 21), (60, 22), (60, 24), (60, 27), (60, 34), (60, 35), (60, 39), (60, 54), (60, 55), (60, 57), (60, 58), (60, 59), (60, 61), (60, 62), (60, 63), (60, 64), (63, 17), (63, 21), (63, 22), (63, 27), (63, 35), (63, 38), (63, 39), (63, 55), (63, 57), (63, 58), (63, 59), (63, 60), (63, 61), (63, 62), (63, 64), (64, 17), (64, 21), (64, 22), (64, 26), (64, 27), (64, 35), (64, 38), (64, 39), (64, 55), (64, 57), (64, 59), (64, 60), (64, 61), (64, 62), (64, 63), (22, 18), (22, 21), (22, 23), (22, 26), (22, 34), (22, 35), (22, 38), (22, 54), (22, 55), (22, 57), (22, 58), (22, 60), (22, 61), (22, 62), (22, 63), (22, 64), (57, 18), (57, 21), (57, 22), (57, 23), (57, 26), (57, 34), (57, 35), (57, 38), (57, 54), (57, 55), (57, 58), (57, 59), (57, 60), (57, 61), (57, 62), (57, 63), (57, 64), (61, 18), (61, 21), (61, 22), (61, 26), (61, 34), (61, 38), (61, 39), (61, 57), (61, 58), (61, 60), (61, 62), (61, 63), (61, 64), (62, 18), (62, 21), (62, 22), (62, 26), (62, 34), (62, 38), (62, 39), (62, 57), (62, 58), (62, 59), (62, 60), (62, 61), (62, 63), (62, 64), (23, 19), (23, 22), (23, 24), (23, 57), (23, 58), (24, 20), (24, 21), (24, 23), (24, 59), (24, 60), (27, 21), (27, 26), (27, 28), (27, 31), (27, 35), (27, 39), (27, 40), (27, 55), (27, 60), (27, 63), (27, 64), (34, 21), (34, 22), (34, 26), (34, 33), (34, 35), (34, 38), (34, 54), (34, 55), (34, 57), (34, 58), (34, 60), (34, 61), (34, 62), (35, 21), (35, 22), (35, 27), (35, 34), (35, 36), (35, 39), (35, 54), (35, 55), (35, 57), (35, 59), (35, 60), (35, 63), (35, 64), (39, 21), (39, 27), (39, 28), (39, 35), (39, 38), (39, 40), (39, 55), (39, 59), (39, 60), (39, 61), (39, 62), (39, 63), (39, 64), (54, 21), (54, 22), (54, 34), (54, 35), (54, 38), (54, 47), (54, 48), (54, 50), (54, 53), (54, 57), (54, 60), (55, 21), (55, 22), (55, 27), (55, 34), (55, 35), (55, 39), (55, 51), (55, 56), (55, 57), (55, 60), (55, 63), (55, 64), (59, 21), (59, 24), (59, 35), (59, 39), (59, 57), (59, 58), (59, 60), (59, 62), (59, 63), (59, 64), (26, 22), (26, 25), (26, 27), (26, 30), (26, 34), (26, 38), (26, 57), (26, 61), (26, 62), (26, 64), (38, 22), (38, 26), (38, 34), (38, 37), (38, 39), (38, 54), (38, 57), (38, 58), (38, 61), (38, 62), (38, 63), (38, 64), (58, 22), (58, 23), (58, 34), (58, 38), (58, 57), (58, 59), (58, 60), (58, 61), (58, 62), (58, 63), (25, 26), (25, 28), (25, 29), (25, 33), (25, 37), (28, 25), (28, 27), (28, 32), (28, 36), (28, 39), (28, 40), (28, 56), (29, 25), (29, 30), (29, 32), (33, 25), (33, 34), (33, 36), (33, 37), (33, 45), (33, 48), (33, 53), (33, 56), (37, 25), (37, 33), (37, 38), (37, 40), (37, 48), (37, 53), (30, 26), (30, 29), (30, 31), (31, 27), (31, 30), (31, 32), (40, 27), (40, 28), (40, 36), (40, 37), (40, 39), (40, 56), (32, 28), (32, 29), (32, 31), (36, 28), (36, 33), (36, 35), (36, 40), (36, 48), (36, 53), (36, 56), (56, 28), (56, 33), (56, 36), (56, 40), (56, 52), (56, 55), (45, 33), (45, 41), (45, 46), (45, 48), (45, 53), (48, 33), (48, 36), (48, 37), (48, 44), (48, 45), (48, 47), (48, 49), (48, 53), (48, 54), (53, 33), (53, 36), (53, 37), (53, 44), (53, 45), (53, 47), (53, 48), (53, 49), (53, 54), (41, 42), (41, 44), (41, 45), (41, 49), (42, 41), (42, 43), (42, 46), (44, 41), (44, 43), (44, 48), (44, 49), (44, 50), (44, 53), (49, 41), (49, 43), (49, 44), (49, 48), (49, 50), (49, 53), (43, 42), (43, 44), (43, 47), (43, 49), (43, 50), (46, 42), (46, 45), (46, 47), (47, 43), (47, 46), (47, 48), (47, 53), (47, 54), (52, 51), (52, 56)]

In [202]:
#For example, accessing edge attributes

consume = G[1][2]['energy_consumption'] #energy consumption from node 1 to node 2
time = G[1][2]['time_travel']

print(f"Energy consumption from node 1 to node 2: {consume} J")
print(f"Time travel from node 1 to node 2: {time} s")

Energy consumption from node 1 to node 2: 85.0 J
Time travel from node 1 to node 2: 5.666666666666667 s

In [203]:
# iterating over all the list of tuples of edges, data=True to get edge attributes.
for source, target, costs in G.edges(data=True): 
    print(f"Arco da {source} a {target}:")
    print(f"    Tempo: {costs['time_travel']}")
    print(f"    Energia: {costs['energy_consumption']}")

Arco da 1 a 2:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 1 a 4:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 1 a 5:
    Tempo: 11.0
    Energia: 550.0
Arco da 1 a 19:
    Tempo: 2.6718699236469
    Energia: 40.078048854703496
Arco da 1 a 20:
    Tempo: 0.6871842709362768
    Energia: 10.307764064044152
Arco da 2 a 1:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 2 a 3:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 2 a 6:
    Tempo: 11.0
    Energia: 550.0
Arco da 2 a 19:
    Tempo: 3.0046260628866577
    Energia: 45.069390943299865
Arco da 2 a 20:
    Tempo: 5.002777006601211
    Energia: 75.04165509901817
Arco da 4 a 1:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 4 a 3:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 4 a 8:
    Tempo: 11.0
    Energia: 550.0
Arco da 5 a 1:
    Tempo: 5.5
    Energia: 55.0
Arco da 5 a 6:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 5 a 8:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 5 a 11:
    Tempo: 4.512328790226961
    Energia: 67.68493185340442
Arco da 5 a 12:
    Tempo: 1.2133516482134197
    Energia: 18.200274723201296
Arco da 19 a 1:
    Tempo: 2.6718699236469
    Energia: 40.078048854703496
Arco da 19 a 2:
    Tempo: 3.0046260628866577
    Energia: 45.069390943299865
Arco da 19 a 18:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 19 a 20:
    Tempo: 2.0
    Energia: 30.0
Arco da 19 a 23:
    Tempo: 4.0
    Energia: 200.0
Arco da 20 a 1:
    Tempo: 0.6871842709362768
    Energia: 10.307764064044152
Arco da 20 a 2:
    Tempo: 5.002777006601211
    Energia: 75.04165509901817
Arco da 20 a 17:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 20 a 19:
    Tempo: 2.0
    Energia: 30.0
Arco da 20 a 24:
    Tempo: 4.0
    Energia: 200.0
Arco da 3 a 2:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 3 a 4:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 3 a 7:
    Tempo: 11.0
    Energia: 550.0
Arco da 6 a 2:
    Tempo: 5.5
    Energia: 55.0
Arco da 6 a 5:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 6 a 7:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 6 a 9:
    Tempo: 2.3154073315749675
    Energia: 34.73110997362451
Arco da 7 a 3:
    Tempo: 5.5
    Energia: 55.0
Arco da 7 a 6:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 7 a 8:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 7 a 10:
    Tempo: 2.3154073315749675
    Energia: 34.73110997362451
Arco da 8 a 4:
    Tempo: 5.5
    Energia: 55.0
Arco da 8 a 5:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 8 a 7:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 8 a 11:
    Tempo: 1.2133516482134197
    Energia: 18.200274723201296
Arco da 8 a 12:
    Tempo: 4.512328790226961
    Energia: 67.68493185340442
Arco da 11 a 5:
    Tempo: 4.512328790226961
    Energia: 67.68493185340442
Arco da 11 a 8:
    Tempo: 1.2133516482134197
    Energia: 18.200274723201296
Arco da 11 a 10:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 11 a 12:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 11 a 15:
    Tempo: 5.0
    Energia: 250.0
Arco da 12 a 5:
    Tempo: 1.2133516482134197
    Energia: 18.200274723201296
Arco da 12 a 8:
    Tempo: 4.512328790226961
    Energia: 67.68493185340442
Arco da 12 a 9:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 12 a 11:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 12 a 16:
    Tempo: 5.0
    Energia: 250.0
Arco da 9 a 6:
    Tempo: 2.3154073315749675
    Energia: 34.73110997362451
Arco da 9 a 10:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 9 a 12:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 9 a 13:
    Tempo: 5.0
    Energia: 250.0
Arco da 10 a 7:
    Tempo: 2.3154073315749675
    Energia: 34.73110997362451
Arco da 10 a 9:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 10 a 11:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 10 a 14:
    Tempo: 5.0
    Energia: 250.0
Arco da 13 a 9:
    Tempo: 2.5
    Energia: 25.0
Arco da 13 a 14:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 13 a 16:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 14 a 10:
    Tempo: 2.5
    Energia: 25.0
Arco da 14 a 13:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 14 a 15:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 15 a 11:
    Tempo: 2.5
    Energia: 25.0
Arco da 15 a 14:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 15 a 16:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 16 a 12:
    Tempo: 2.5
    Energia: 25.0
Arco da 16 a 13:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 16 a 15:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 17 a 18:
    Tempo: 2.0
    Energia: 30.0
Arco da 17 a 20:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 17 a 21:
    Tempo: 4.0
    Energia: 200.0
Arco da 17 a 50:
    Tempo: 5.4768198396109
    Energia: 82.15229759416349
Arco da 17 a 51:
    Tempo: 2.1592179654268864
    Energia: 32.3882694814033
Arco da 17 a 60:
    Tempo: 4.0
    Energia: 203.0
Arco da 17 a 63:
    Tempo: 5.5
    Energia: 280.8309518948453
Arco da 17 a 64:
    Tempo: 5.5
    Energia: 278.0
Arco da 18 a 17:
    Tempo: 2.0
    Energia: 30.0
Arco da 18 a 19:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 18 a 22:
    Tempo: 4.0
    Energia: 200.0
Arco da 18 a 50:
    Tempo: 3.4826554364290607
    Energia: 52.23983154643591
Arco da 18 a 51:
    Tempo: 4.146752410689063
    Energia: 62.20128616033595
Arco da 18 a 57:
    Tempo: 4.0
    Energia: 202.0
Arco da 18 a 61:
    Tempo: 5.5
    Energia: 277.0
Arco da 18 a 62:
    Tempo: 5.5
    Energia: 280.3851648071345
Arco da 21 a 17:
    Tempo: 2.0
    Energia: 20.0
Arco da 21 a 22:
    Tempo: 2.0
    Energia: 30.0
Arco da 21 a 24:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 21 a 27:
    Tempo: 1.6666666666666667
    Energia: 100.0
Arco da 21 a 34:
    Tempo: 3.0666666666666664
    Energia: 46.0
Arco da 21 a 35:
    Tempo: 1.0
    Energia: 15.0
Arco da 21 a 39:
    Tempo: 1.5
    Energia: 90.0
Arco da 21 a 54:
    Tempo: 5.4768198396109
    Energia: 82.15229759416349
Arco da 21 a 55:
    Tempo: 2.1592179654268864
    Energia: 32.3882694814033
Arco da 21 a 57:
    Tempo: 1.8666666666666665
    Energia: 28.0
Arco da 21 a 59:
    Tempo: 2.009975124224178
    Energia: 30.14962686336267
Arco da 21 a 60:
    Tempo: 0.20000000000000004
    Energia: 3.0000000000000004
Arco da 21 a 61:
    Tempo: 1.8666666666666665
    Energia: 103.0
Arco da 21 a 62:
    Tempo: 1.896195020443719
    Energia: 103.44292530665578
Arco da 21 a 63:
    Tempo: 1.5
    Energia: 80.8309518948453
Arco da 21 a 64:
    Tempo: 1.5
    Energia: 78.0
Arco da 50 a 17:
    Tempo: 5.4768198396109
    Energia: 82.15229759416349
Arco da 50 a 18:
    Tempo: 3.4826554364290607
    Energia: 52.23983154643591
Arco da 50 a 43:
    Tempo: 2.6999999999999997
    Energia: 40.5
Arco da 50 a 44:
    Tempo: 7.333333333333333
    Energia: 110.0
Arco da 50 a 49:
    Tempo: 7.333333333333333
    Energia: 110.0
Arco da 50 a 54:
    Tempo: 4.0
    Energia: 200.0
Arco da 51 a 17:
    Tempo: 2.1592179654268864
    Energia: 32.3882694814033
Arco da 51 a 18:
    Tempo: 4.146752410689063
    Energia: 62.20128616033595
Arco da 51 a 52:
    Tempo: 7.333333333333333
    Energia: 110.0
Arco da 51 a 55:
    Tempo: 4.0
    Energia: 200.0
Arco da 60 a 17:
    Tempo: 2.0
    Energia: 23.0
Arco da 60 a 21:
    Tempo: 0.20000000000000004
    Energia: 3.0000000000000004
Arco da 60 a 22:
    Tempo: 1.8
    Energia: 27.0
Arco da 60 a 24:
    Tempo: 4.670950414827563
    Energia: 70.06425622241343
Arco da 60 a 27:
    Tempo: 1.7938165396098282
    Energia: 101.90724809414742
Arco da 60 a 34:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 60 a 35:
    Tempo: 1.2
    Energia: 18.0
Arco da 60 a 39:
    Tempo: 1.5
    Energia: 93.0
Arco da 60 a 54:
    Tempo: 5.277204647243547
    Energia: 79.1580697086532
Arco da 60 a 55:
    Tempo: 2.3570226039551585
    Energia: 35.35533905932738
Arco da 60 a 57:
    Tempo: 1.6666666666666667
    Energia: 25.0
Arco da 60 a 58:
    Tempo: 2.6034165586355513
    Energia: 39.05124837953327
Arco da 60 a 59:
    Tempo: 2.0
    Energia: 30.0
Arco da 60 a 61:
    Tempo: 1.6666666666666667
    Energia: 100.0
Arco da 60 a 62:
    Tempo: 1.6996731711975948
    Energia: 100.49509756796392
Arco da 60 a 63:
    Tempo: 1.5
    Energia: 80.0
Arco da 60 a 64:
    Tempo: 1.5
    Energia: 75.0
Arco da 63 a 17:
    Tempo: 2.75
    Energia: 33.3309518948453
Arco da 63 a 21:
    Tempo: 0.75
    Energia: 13.3309518948453
Arco da 63 a 22:
    Tempo: 1.8306040290327976
    Energia: 34.95906043549196
Arco da 63 a 27:
    Tempo: 2.053722906766582
    Energia: 30.805843601498726
Arco da 63 a 35:
    Tempo: 1.2454361128179603
    Energia: 26.181541692269406
Arco da 63 a 38:
    Tempo: 2.8859814429217816
    Energia: 43.289721643826724
Arco da 63 a 39:
    Tempo: 1.2454361128179603
    Energia: 18.681541692269406
Arco da 63 a 55:
    Tempo: 2.3333333333333335
    Energia: 42.5
Arco da 63 a 57:
    Tempo: 1.6996731711975948
    Energia: 32.995097567963924
Arco da 63 a 58:
    Tempo: 2.3570226039551585
    Energia: 42.85533905932738
Arco da 63 a 59:
    Tempo: 1.6666666666666667
    Energia: 32.5
Arco da 63 a 60:
    Tempo: 0.75
    Energia: 12.5
Arco da 63 a 61:
    Tempo: 1.6996731711975948
    Energia: 25.495097567963924
Arco da 63 a 62:
    Tempo: 1.6666666666666667
    Energia: 25.0
Arco da 63 a 64:
    Tempo: 0.3333333333333333
    Energia: 5.0
Arco da 64 a 17:
    Tempo: 2.75
    Energia: 30.5
Arco da 64 a 21:
    Tempo: 0.75
    Energia: 10.5
Arco da 64 a 22:
    Tempo: 1.8
    Energia: 34.5
Arco da 64 a 26:
    Tempo: 2.515728301881761
    Energia: 37.73592452822642
Arco da 64 a 27:
    Tempo: 1.7938165396098282
    Energia: 26.907248094147423
Arco da 64 a 35:
    Tempo: 1.2
    Energia: 25.5
Arco da 64 a 38:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 64 a 39:
    Tempo: 1.2
    Energia: 18.0
Arco da 64 a 55:
    Tempo: 2.3570226039551585
    Energia: 42.85533905932738
Arco da 64 a 57:
    Tempo: 1.6666666666666667
    Energia: 32.5
Arco da 64 a 59:
    Tempo: 2.0
    Energia: 37.5
Arco da 64 a 60:
    Tempo: 0.75
    Energia: 7.5
Arco da 64 a 61:
    Tempo: 1.6666666666666667
    Energia: 25.0
Arco da 64 a 62:
    Tempo: 1.6996731711975948
    Energia: 25.495097567963924
Arco da 64 a 63:
    Tempo: 0.3333333333333333
    Energia: 5.0
Arco da 22 a 18:
    Tempo: 2.0
    Energia: 20.0
Arco da 22 a 21:
    Tempo: 2.0
    Energia: 30.0
Arco da 22 a 23:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 22 a 26:
    Tempo: 1.5
    Energia: 95.6155281280883
Arco da 22 a 34:
    Tempo: 1.0666666666666667
    Energia: 16.0
Arco da 22 a 35:
    Tempo: 3.0
    Energia: 45.0
Arco da 22 a 38:
    Tempo: 1.5
    Energia: 91.0
Arco da 22 a 54:
    Tempo: 3.4826554364290607
    Energia: 52.23983154643591
Arco da 22 a 55:
    Tempo: 4.146752410689063
    Energia: 62.20128616033595
Arco da 22 a 57:
    Tempo: 0.1333333333333333
    Energia: 1.9999999999999996
Arco da 22 a 58:
    Tempo: 2.0044395171163876
    Energia: 30.066592756745813
Arco da 22 a 60:
    Tempo: 1.8
    Energia: 27.0
Arco da 22 a 61:
    Tempo: 1.5
    Energia: 77.0
Arco da 22 a 62:
    Tempo: 1.5
    Energia: 80.3851648071345
Arco da 22 a 63:
    Tempo: 1.8306040290327976
    Energia: 102.45906043549196
Arco da 22 a 64:
    Tempo: 1.8
    Energia: 102.0
Arco da 57 a 18:
    Tempo: 2.0
    Energia: 22.0
Arco da 57 a 21:
    Tempo: 1.8666666666666665
    Energia: 28.0
Arco da 57 a 22:
    Tempo: 0.1333333333333333
    Energia: 1.9999999999999996
Arco da 57 a 23:
    Tempo: 4.668571040003092
    Energia: 70.02856560004639
Arco da 57 a 26:
    Tempo: 1.5
    Energia: 96.18962010041709
Arco da 57 a 34:
    Tempo: 1.2
    Energia: 18.0
Arco da 57 a 35:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 57 a 38:
    Tempo: 1.5
    Energia: 93.0
Arco da 57 a 54:
    Tempo: 3.6153991634550002
    Energia: 54.230987451825
Arco da 57 a 55:
    Tempo: 4.013864859597432
    Energia: 60.20797289396148
Arco da 57 a 58:
    Tempo: 2.0
    Energia: 30.0
Arco da 57 a 59:
    Tempo: 2.6034165586355513
    Energia: 39.05124837953327
Arco da 57 a 60:
    Tempo: 1.6666666666666667
    Energia: 25.0
Arco da 57 a 61:
    Tempo: 1.5
    Energia: 75.0
Arco da 57 a 62:
    Tempo: 1.5
    Energia: 80.0
Arco da 57 a 63:
    Tempo: 1.6996731711975948
    Energia: 100.49509756796392
Arco da 57 a 64:
    Tempo: 1.6666666666666667
    Energia: 100.0
Arco da 61 a 18:
    Tempo: 2.75
    Energia: 29.5
Arco da 61 a 21:
    Tempo: 1.8666666666666665
    Energia: 35.5
Arco da 61 a 22:
    Tempo: 0.75
    Energia: 9.5
Arco da 61 a 26:
    Tempo: 1.412641340027806
    Energia: 21.18962010041709
Arco da 61 a 34:
    Tempo: 1.2
    Energia: 25.5
Arco da 61 a 38:
    Tempo: 1.2
    Energia: 18.0
Arco da 61 a 39:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 61 a 57:
    Tempo: 0.75
    Energia: 7.5
Arco da 61 a 58:
    Tempo: 2.0
    Energia: 37.5
Arco da 61 a 60:
    Tempo: 1.6666666666666667
    Energia: 32.5
Arco da 61 a 62:
    Tempo: 0.3333333333333333
    Energia: 5.0
Arco da 61 a 63:
    Tempo: 1.6996731711975948
    Energia: 25.495097567963924
Arco da 61 a 64:
    Tempo: 1.6666666666666667
    Energia: 25.0
Arco da 62 a 18:
    Tempo: 2.75
    Energia: 32.8851648071345
Arco da 62 a 21:
    Tempo: 1.896195020443719
    Energia: 35.94292530665578
Arco da 62 a 22:
    Tempo: 0.75
    Energia: 12.885164807134505
Arco da 62 a 26:
    Tempo: 1.730767331432956
    Energia: 25.961509971494337
Arco da 62 a 34:
    Tempo: 1.2454361128179603
    Energia: 26.181541692269406
Arco da 62 a 38:
    Tempo: 1.2454361128179603
    Energia: 18.681541692269406
Arco da 62 a 39:
    Tempo: 2.8859814429217816
    Energia: 43.289721643826724
Arco da 62 a 57:
    Tempo: 0.75
    Energia: 12.5
Arco da 62 a 58:
    Tempo: 1.6666666666666667
    Energia: 32.5
Arco da 62 a 59:
    Tempo: 2.3570226039551585
    Energia: 42.85533905932738
Arco da 62 a 60:
    Tempo: 1.6996731711975948
    Energia: 32.995097567963924
Arco da 62 a 61:
    Tempo: 0.3333333333333333
    Energia: 5.0
Arco da 62 a 63:
    Tempo: 1.6666666666666667
    Energia: 25.0
Arco da 62 a 64:
    Tempo: 1.6996731711975948
    Energia: 25.495097567963924
Arco da 23 a 19:
    Tempo: 2.0
    Energia: 20.0
Arco da 23 a 22:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 23 a 24:
    Tempo: 2.0
    Energia: 30.0
Arco da 23 a 57:
    Tempo: 4.668571040003092
    Energia: 70.02856560004639
Arco da 23 a 58:
    Tempo: 2.6699979192667715
    Energia: 40.049968789001575
Arco da 24 a 20:
    Tempo: 2.0
    Energia: 20.0
Arco da 24 a 21:
    Tempo: 4.666666666666667
    Energia: 70.0
Arco da 24 a 23:
    Tempo: 2.0
    Energia: 30.0
Arco da 24 a 59:
    Tempo: 2.674156149350877
    Energia: 40.11234224026316
Arco da 24 a 60:
    Tempo: 4.670950414827563
    Energia: 70.06425622241343
Arco da 27 a 21:
    Tempo: 1.6666666666666667
    Energia: 32.5
Arco da 27 a 26:
    Tempo: 3.3333333333333335
    Energia: 50.0
Arco da 27 a 28:
    Tempo: 3.6666666666666665
    Energia: 55.0
Arco da 27 a 31:
    Tempo: 4.5
    Energia: 225.0
Arco da 27 a 35:
    Tempo: 1.3333333333333333
    Energia: 27.5
Arco da 27 a 39:
    Tempo: 1.3333333333333333
    Energia: 20.0
Arco da 27 a 40:
    Tempo: 5.666666666666667
    Energia: 85.0
Arco da 27 a 55:
    Tempo: 2.015495527710797
    Energia: 37.73243291566195
Arco da 27 a 60:
    Tempo: 1.7938165396098282
    Energia: 34.40724809414742
Arco da 27 a 63:
    Tempo: 2.053722906766582
    Energia: 30.805843601498726
Arco da 27 a 64:
    Tempo: 1.7938165396098282
    Energia: 26.907248094147423
Arco da 34 a 21:
    Tempo: 3.0666666666666664
    Energia: 46.0
Arco da 34 a 22:
    Tempo: 1.0666666666666667
    Energia: 16.0
Arco da 34 a 26:
    Tempo: 1.521694961401777
    Energia: 97.82542442102665
Arco da 34 a 33:
    Tempo: 7.0
    Energia: 105.0
Arco da 34 a 35:
    Tempo: 4.066666666666666
    Energia: 61.0
Arco da 34 a 38:
    Tempo: 1.5
    Energia: 75.0
Arco da 34 a 54:
    Tempo: 2.423037579384833
    Energia: 36.345563690772494
Arco da 34 a 55:
    Tempo: 5.210672807911769
    Energia: 78.16009211867653
Arco da 34 a 57:
    Tempo: 1.2
    Energia: 18.0
Arco da 34 a 58:
    Tempo: 2.3323807579381204
    Energia: 34.9857113690718
Arco da 34 a 60:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 34 a 61:
    Tempo: 1.5
    Energia: 93.0
Arco da 34 a 62:
    Tempo: 1.5
    Energia: 93.6815416922694
Arco da 35 a 21:
    Tempo: 1.0
    Energia: 15.0
Arco da 35 a 22:
    Tempo: 3.0
    Energia: 45.0
Arco da 35 a 27:
    Tempo: 1.5
    Energia: 95.0
Arco da 35 a 34:
    Tempo: 4.066666666666666
    Energia: 61.0
Arco da 35 a 36:
    Tempo: 7.0
    Energia: 105.0
Arco da 35 a 39:
    Tempo: 1.5
    Energia: 75.0
Arco da 35 a 54:
    Tempo: 6.475252032846975
    Energia: 97.12878049270464
Arco da 35 a 55:
    Tempo: 1.1813363431112902
    Energia: 17.720045146669353
Arco da 35 a 57:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 35 a 59:
    Tempo: 2.3323807579381204
    Energia: 34.9857113690718
Arco da 35 a 60:
    Tempo: 1.2
    Energia: 18.0
Arco da 35 a 63:
    Tempo: 1.5
    Energia: 93.6815416922694
Arco da 35 a 64:
    Tempo: 1.5
    Energia: 93.0
Arco da 39 a 21:
    Tempo: 1.0
    Energia: 22.5
Arco da 39 a 27:
    Tempo: 1.3333333333333333
    Energia: 20.0
Arco da 39 a 28:
    Tempo: 5.0
    Energia: 75.0
Arco da 39 a 35:
    Tempo: 0.75
    Energia: 7.5
Arco da 39 a 38:
    Tempo: 4.066666666666666
    Energia: 61.0
Arco da 39 a 40:
    Tempo: 7.0
    Energia: 105.0
Arco da 39 a 55:
    Tempo: 1.1813363431112902
    Energia: 25.220045146669353
Arco da 39 a 59:
    Tempo: 2.3323807579381204
    Energia: 42.4857113690718
Arco da 39 a 60:
    Tempo: 1.2
    Energia: 25.5
Arco da 39 a 61:
    Tempo: 2.8666666666666667
    Energia: 43.0
Arco da 39 a 62:
    Tempo: 2.8859814429217816
    Energia: 43.289721643826724
Arco da 39 a 63:
    Tempo: 1.2454361128179603
    Energia: 18.681541692269406
Arco da 39 a 64:
    Tempo: 1.2
    Energia: 18.0
Arco da 54 a 21:
    Tempo: 5.4768198396109
    Energia: 82.15229759416349
Arco da 54 a 22:
    Tempo: 3.4826554364290607
    Energia: 52.23983154643591
Arco da 54 a 34:
    Tempo: 2.423037579384833
    Energia: 36.345563690772494
Arco da 54 a 35:
    Tempo: 6.475252032846975
    Energia: 97.12878049270464
Arco da 54 a 38:
    Tempo: 2.423037579384833
    Energia: 111.3455636907725
Arco da 54 a 47:
    Tempo: 2.6999999999999997
    Energia: 40.5
Arco da 54 a 48:
    Tempo: 7.333333333333333
    Energia: 110.0
Arco da 54 a 50:
    Tempo: 2.0
    Energia: 20.0
Arco da 54 a 53:
    Tempo: 7.333333333333333
    Energia: 110.0
Arco da 54 a 57:
    Tempo: 3.6153991634550002
    Energia: 54.230987451825
Arco da 54 a 60:
    Tempo: 5.277204647243547
    Energia: 79.1580697086532
Arco da 55 a 21:
    Tempo: 2.1592179654268864
    Energia: 32.3882694814033
Arco da 55 a 22:
    Tempo: 4.146752410689063
    Energia: 62.20128616033595
Arco da 55 a 27:
    Tempo: 2.015495527710797
    Energia: 105.23243291566195
Arco da 55 a 34:
    Tempo: 5.210672807911769
    Energia: 78.16009211867653
Arco da 55 a 35:
    Tempo: 1.1813363431112902
    Energia: 17.720045146669353
Arco da 55 a 39:
    Tempo: 1.5
    Energia: 92.72004514666935
Arco da 55 a 51:
    Tempo: 2.0
    Energia: 20.0
Arco da 55 a 56:
    Tempo: 7.333333333333333
    Energia: 110.0
Arco da 55 a 57:
    Tempo: 4.013864859597432
    Energia: 60.20797289396148
Arco da 55 a 60:
    Tempo: 2.3570226039551585
    Energia: 35.35533905932738
Arco da 55 a 63:
    Tempo: 2.3333333333333335
    Energia: 110.0
Arco da 55 a 64:
    Tempo: 2.3570226039551585
    Energia: 110.35533905932738
Arco da 59 a 21:
    Tempo: 2.009975124224178
    Energia: 30.14962686336267
Arco da 59 a 24:
    Tempo: 2.674156149350877
    Energia: 40.11234224026316
Arco da 59 a 35:
    Tempo: 2.3323807579381204
    Energia: 34.9857113690718
Arco da 59 a 39: